### ISSUE TITLE
Fontawesome.com issues

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#14]
**Describe the bug**
Sidebar is invisible if fontawesome.com is not reachable from any particular PC (elements are there but images are not). Tested from two different PCs where fontawesome.com is reachable from one location but not another

**To Reproduce**
Visit on any browser
GET https://use.fontawesome.com/releases/v5.3.1/css/all.css net::ERR_NAME_RESOLUTION_FAILED should be triggering in console

**Expected behavior**
Sidebar should be visible

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: N/A

**Additional context**
Possibly needs a fallback in the event fontawesome.com is not reachable

**Comment by malulleybovo** [comment]
Although achievable by simply blocking the execution of the fontawesome script in your browser, this issue became more apparent a couple days ago when the service provided by fontawesome went down for almost a day. This caused any fontawesome icons dynamically loaded via their service to not show up, resulting in this application and also many other dependent commercial websites (yes, that is unfortunately right) to not load correctly. The solution to this is to have alternative icons (ideally stored locally). I am investigating potential solutions.

**Comment by malulleybovo** [comment]
Issue has been resolved and is available in the latest release.
