### ISSUE TITLE
Use S-affixes as "junk"

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#15]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to choose an S-class ability, such as any of the S1-S4 affixes to be treated as junk. The difference between this and using regular junk is that it is a guaranteed 100% assuming the weapon supports it, which also impacts the stage success calculation. 

**Describe the solution you'd like**
When choosing junk, the user should be able to choose between either "Junk A" or "S1 Junk" as options, for example. This should apply all the way to S4.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by malulleybovo** [comment]
I will investigate a way to allow generic SSAs and include it in a future release.

**Comment by malulleybovo** [comment]
Issue has been resolved and is available in the latest release.
