### ISSUE TITLE
Missing +15% boost week on top of Ripper/Ice

### ISSUE THREAD

**Issue by GHNeko** [malulleybovo/PSO2AffixingAssistant#18]
seems like sega is doing 15% boost weeks now, also i couldnt find all 3 rippers, and I'm sure ice was missing.

**Comment by malulleybovo** [comment]
+15% success rate bonus from boost week is now available in the latest version.
Regarding the ripper abilities, they will be available soon with the other abilities missing.

**Comment by malulleybovo** [comment]
Missing ripper abilities are now available in the latest version.
