### ISSUE TITLE
Persona Reverie is missing

### ISSUE THREAD

**Issue by HunterGraubard** [malulleybovo/PSO2AffixingAssistant#2]
The Persona Reverie affix seems to be missing. It gives +40 to all ATK stats, and -20 to all DEF stats.

Edit: Mana Reverie is also missing. It gives +50 to all ATK stats, +20 HP, and +4 PP.

**Comment by HunterGraubard** [comment]
Reverie Catalyst also seems to be missing.

**Comment by malulleybovo** [comment]
Thanks for the heads up. Support has been added for those abilities.
