### ISSUE TITLE
Feature Request: Filter Out Affixes with syntax

### ISSUE THREAD

**Issue by GHNeko** [malulleybovo/PSO2AffixingAssistant#20]
Requesting the ability to have the search filter filter out affixes with similar syntax's in search engines.

For example, when you click the PP Radio element, you can then type in "-Soul" and the filter will ignore all affixes with "Soul" in the string.

Would make searching for affixes more streamlined.

**Comment by malulleybovo** [comment]
Liked your suggestion. However, text syntax did not feel like it would be very intuitive to most users. So I went all out on my UX thinking and came up with an interesting solution. The implementation of this request is now available in the latest release. Hope it feels great to use. Enjoy.

**Comment by GHNeko** [comment]
Oh this is great thanks a lot!
