### ISSUE TITLE
New Affix Items

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#21]
As of this week, the following items can now be affixed using items from the limited AC Scratch Exchange Shop:

- Sentence Power
- Sentence Shoot
- Sentence Tech
- Ether Soul
- Factor Catalyst

Other SOPs also got added, please see the following link for more info (Japanese only):
https://pso2roboarks.jp/gennteiacrisaikurushop

**Comment by velocity7** [comment]
FYI, as of this week Doom Break 3 got added as SAF from the new Orb-series weapons.

**Comment by GHNeko** [comment]
Just wanted to add that there are several new SOP/SSA; specifically for units. We now have S6, S7, and S8 SSA, and S5 will be coming in 2 weeks as well. The existing S6-S8 can be found on visiphone. If you want me to list them for you; lemme know.

**Comment by LaquedemPF-zz** [comment]
Another update; Lamia Series comes with several useful SAFs that are not included in the simulator yet. This includes Factor Catalyst as SAF for Wired Lances. Details for that are probably on SWiki... or with a lot of luck on Arks Visiphone Wiki.

**Comment by ThatOneOutlier** [comment]
Grand Power/Tech/Shoot/Stamina has been added

**Comment by DEndries8** [comment]
I'm interested in contributing.  A list of the missing affixes would be appreciated; I can gather the relevant info and write the code, just need to know what I'm looking for.

**Comment by malulleybovo** [comment]
I apologize for the late response! I have had an issue with my GitHub password for some time and could not log in to update my Projects... Regardless, I am back and you can expect some updates on this project in the near future!

I will be going over the updates listed in this issue and confronting them with any other information I find.

Regarding contributing, anyone is more than welcome to contribute! I have been meaning to include a document on how to do that for this project, as well as some documentation about the project architecture and how to update the "affix database". More on that to come when I find some free time.

**Comment by malulleybovo** [comment]
As promised, the Affixing Assistant has been updated. And it comes in the first official release of the PSO2 Affixing Assistant: v1.0.0! It took quite some time to update since I added in an automation tool to help with future updates, fixed a few things, and released a documentation on how to contribute to this project. To contribute, take a look at CONTRIBUTING.md.
