### ISSUE TITLE
All affixes can be transferred now

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#22]
**Is your feature request related to a problem? Please describe.**
All affixes can now be transferred using affix tickets with 100% transfer rate. SOPs don't transfer using this method.

**Describe the solution you'd like**
Probably modification to system to allow affix tickets as an option for all affixes (including ones that don't have a valid transfer method).

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by malulleybovo** [comment]
Thanks for the note! If you are referencing the new Special Ability Transplants, that will have to be added to the project’s roadmap as a new feature since it requires a different number of extra items depending on the scenario. When I find some free time, I’ll try to think about a nice way to include this.

**Comment by malulleybovo** [comment]
After a long wait, Special Ability Transplants have finally been added to the Affixing Assistant.
It took a great deal of searching, thinking, and designing to get it to fit nicely with the affixing flow.
The new feature is currently only available in Debug Mode while I assess it for any lingering bugs.
[A preview of the feature can be found here](https://malulleybovo.github.io/PSO2AffixingAssistant/index.debug.html).
Be warned that there may still be bugs in the link above which could impact functionality.

**Comment by malulleybovo** [comment]
The new feature is now live from v1.1.0+ of the Affixing Assistant along with an update in the Database.
You can use it by clicking on the *plus* button on the sidebar to create a new goal or the "Transplant" button on any fodder in the formula. 
When creating a new goal, you will now be given two choices: "Transplant" (to transplant abilities to the goal) and "Affix" (to affix abilities to the goal).
Visually, Affixing stages will show in the usual color (gray for dark mode, and light blue for bright mode) while Transplant stages will show in a different color (blue for dark mode, and light gray for bright mode).
Make sure to check it out.
