### ISSUE TITLE
Issue with trying to contribute to the affixing assistant.

### ISSUE THREAD

**Issue by GHNeko** [malulleybovo/PSO2AffixingAssistant#23]
![](http://puu.sh/FtD3R/996272565b.png)

Got met with this error in regards to seemingly pulling some info from arks-layer.com

**Comment by malulleybovo** [comment]
Thank you for reporting this issue. It seems one of the dependencies in the UpdateManager was moved to another address. This issue has been corrected in commit 97d399890ac9adb8a7528603765179bf57e191ef. Please update your clone and try again.
