### ISSUE TITLE
Soul Receptor

### ISSUE THREAD

**Issue by Inabi-Ibani** [malulleybovo/PSO2AffixingAssistant#25]
**Describe the bug**
Soul Receptor cannot be selected to be added with a soul in the assistant. 

**To Reproduce**
1.Select a soul or Soul Receptor as an affix to add
2.Attempt to select the other to add, it will then replace instead of add.

**Screenshots**
An in game screen shot of being able to add both at once:
https://i.imgur.com/mpfsa5Y.jpg

**Comment by malulleybovo** [comment]
Thanks for reporting this bug. This issue has been resolved in the latest version.
