### ISSUE TITLE
Reverie Catalyst and Omega Memoria cannot be selected as a transplant item

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#26]
**Describe the bug**
Reverie Catalyst and Omega Memoria cannot be selected as a transplant item

**To Reproduce**
Attempt to transplant and select either Reverie Catalyst or Omega Memoria

**Expected behavior**
Either of the options should be transplantable.

**Comment by malulleybovo** [comment]
I don't think I understood your issue. The said abilities do seem transplantable as per the evidence below:
![image](https://user-images.githubusercontent.com/14852459/86542898-7483ca80-bedf-11ea-80f2-8e6199078cce.png)
Could you clarify (or even exemplify) where you think something is going wrong?

**Comment by velocity7** [comment]
The bug is that Omega Memoria and Reverie Catalyst have capsules that exist for them (on Ship 2 they're 40M each). I can't choose either as an item when transplanting:

![image](https://user-images.githubusercontent.com/11874183/86543671-c718b300-beee-11ea-9e8f-dadfda0834d6.png)

**Comment by malulleybovo** [comment]
As mentioned in issue https://github.com/malulleybovo/PSO2AffixingAssistant/issues/29, this seems to be due to the Assistant being outdated and not knowing that such Add Ability Items (or capsules) exist.

**Comment by velocity7** [comment]
Not sure what the database needs to read from the swiki, but the affix items in question are definitely [there](https://pso2.swiki.jp/index.php?%E7%89%B9%E6%AE%8A%E8%83%BD%E5%8A%9B%E8%BF%BD%E5%8A%A0&word=%E7%B6%99%E6%89%BF):

![image](https://user-images.githubusercontent.com/11874183/86557720-09f57d80-bf25-11ea-9821-327f813fe315.png)
![image](https://user-images.githubusercontent.com/11874183/86557676-ea5e5500-bf24-11ea-9706-0ca5e50b412a.png)

**Comment by malulleybovo** [comment]
A new version is in the works and will address this issue. I will update this issue when I have more news.

**Comment by malulleybovo** [comment]
Please find these changes in v1.2.0 of the Affixing Assistant. Thank you again for reporting!
