### ISSUE TITLE
Setting to force an affix to 100% due to Unit SAFs?

### ISSUE THREAD

**Issue by GHNeko** [malulleybovo/PSO2AffixingAssistant#32]
13* units were updated to give them SAFs, meaning that upon getting them to +10, they will provide the typical SAF affix to put on them such as Lesser Stat 4 or Darkness Soul. However in the assistant, there is no method of forcing an affix to 100% with a single copy to replicate the usefulness of SAFs. Doesn't seem like that's the case for weapons either too, to be honest.

**Comment by malulleybovo** [comment]
Hello, thank you for reporting. The Affixing Assistant does support SAFs for the abilities that it knows have SAFs. With time, more abilities receive SAFs in game, which consequently makes the Assistant outdated. Thus you may run into a scenario in which you try to find the SAF option for an ability but it is not listed. A new version is in the works which also include updates on SAFs, so hopefully it addresses this issue.

**Comment by malulleybovo** [comment]
Please find these changes in v1.2.0 of the Affixing Assistant. Thank you again for reporting!
