### ISSUE TITLE
Guardian Soul, Absolute Glare and related affixes

### ISSUE THREAD

**Issue by velocity7** [malulleybovo/PSO2AffixingAssistant#33]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
New affixes added

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gesori-pro** [comment]
I added it.
But I couldn't add SSA(S Ability)

**Comment by malulleybovo** [comment]
Hello. There is a pull request still in review to address this (https://github.com/malulleybovo/PSO2AffixingAssistant/pull/34). Thank you for contributing @focuslite! I have been struggling to find time to put in this project so it might take a bit longer to update it. I hope you understand.

**Comment by malulleybovo** [comment]
Please find these changes in v1.2.0 of the Affixing Assistant. Thank you again for reporting!
