### ISSUE TITLE
Add Ability Capsules for Mana Rev, Ether Factor, Astral Soul

### ISSUE THREAD

**Issue by ThatOneOutlier** [malulleybovo/PSO2AffixingAssistant#35]
They were recently added in the mission pass exchange

**Comment by nandadytm** [comment]
~~Apparently there is no data for the caps in Arks-Layer Ability Simulator database yet, so we'll have to wait for them to add it.~~

Scratch that, it is possible to add it now. I'll be updating my branch and see how it goes.

**Comment by malulleybovo** [comment]
Hello. The pending update will be added as soon as I find time to put in this project. Thank you for understanding. If you have an update in the works, please submit a pull request when you have a version that builds without warning and that adds functionality without issues.

**Comment by malulleybovo** [comment]
Please find these changes in v1.2.0 of the Affixing Assistant. Thank you again for reporting!
