### ISSUE TITLE
Add Stat VI synthesis rates.

### ISSUE THREAD

**Issue by acepCA** [malulleybovo/PSO2AffixingAssistant#38]
**Is your feature request related to a problem? Please describe.**
Stat VI is now synthesizable through normal affixing in both NA and JP.

**Describe the solution you'd like**
Add synthesis rates to Stat VI, show below:
	60% : Stat VI, Stat VI, Stat VI
	40% : Stat VI, Stat VI
	30% : Stat V, Stat V, Stat V
	20% : Stat VI
	10% : Stat V, Stat V

**Additional context**
Testing done on NA servers.
https://streamable.com/ucete6

**Comment by acepCA** [comment]
Also synthesizes with Attack Receptors at 100% rate.
https://streamable.com/5dg5qh

**Comment by malulleybovo** [comment]
Hello, thank you for reporting this change. This is being included in the next update.

**Comment by malulleybovo** [comment]
Please find these changes in v1.2.0 of the Affixing Assistant. Thank you again for reporting!
