### ISSUE TITLE
OP name and value is not match

### ISSUE THREAD

**Issue by bdm1v4s** [malulleybovo/PSO2AffixingAssistant#40]
**Screenshots**

![image](https://user-images.githubusercontent.com/72687642/95674288-b65c9500-0be1-11eb-939d-fd7284896227.png)
Correct name is センテンス・トリプル

![image](https://user-images.githubusercontent.com/72687642/95674319-f3288c00-0be1-11eb-9cee-896ac4d6134c.png)
description of mouse over is correct 
![image](https://user-images.githubusercontent.com/72687642/95674360-4d295180-0be2-11eb-912d-9a430553ba17.png)

**Comment by malulleybovo** [comment]
Hello, thank you for reporting this issue. This will be addressed in the next release.

**Comment by malulleybovo** [comment]
Please find these changes in v1.2.0 of the Affixing Assistant. Thank you again for reporting!
