### ISSUE TITLE
Wrong success chance of Mana Reverie, Astral Soul, and Ether Factor

### ISSUE THREAD

**Issue by nandadytm** [malulleybovo/PSO2AffixingAssistant#41]
**Describe the bug**
Wrong success chance when making Mana Reverie, Astral Soul, and Ether Factor (newest capsules affix).

**To Reproduce**
1. Add any of the mentioned affix in to the affix list.
2. Select the 60% version of it (4x catalyst and 1x corresponding reverie/soul/factor).

**Expected behavior**
Success chance should be 60%, not 100%, because we're not using capsule.

**Additional context**
This was fixed in PR #37 but somehow the changes are not included with the update.

**Comment by malulleybovo** [comment]
Hello, thank you for reporting this issue. I noticed some changes in PR https://github.com/malulleybovo/PSO2AffixingAssistant/pull/37 pertaining to the calculation of success rate of Add Abilities but it somehow slipped through the update. Thank you for noticing that, this particular calculation has been inaccurate for longer that it seems. I will make sure to include the fix to this in the next release.

**Comment by malulleybovo** [comment]
Issue resolved in the latest version.
