### ISSUE TITLE
Stamina VI identical to Stamina V and stacks

### ISSUE THREAD

**Issue by 3geek14** [malulleybovo/PSO2AffixingAssistant#43]
**Describe the bug**
Stamina VI and Stamina V both show as giving +70 HP, and it's possible to put both on the same item.

**To Reproduce**
1. Go to 'check or change the affixing goal'
2. Click on 'Stamina VI'
3. Click on 'Stamina V'

**Expected behavior**
Only one should be active, and Stamina VI should give +80

**Screenshots**
![image](https://user-images.githubusercontent.com/23459960/96543506-86ad2d00-1272-11eb-8631-542b73816547.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 86.0.4240.75 (Official Build) (64-bit)

**Comment by 3geek14** [comment]
Update: I see that I was using someone else's fork of your simulator for the NA version. Your simulator does not have the bug where both can be used together, but it does still have the bug where it treats Stamina VI as adding only 70 HP.

**Comment by malulleybovo** [comment]
Issue has been fixed in v1.2.2.
