### ISSUE TITLE
few bug&feature that i found

### ISSUE THREAD

**Issue by vo0029** [malulleybovo/PSO2AffixingAssistant#44]
so. first i suggest that when do multiple transplant. i can downslot the later one without leaving the junk in 
![image](https://user-images.githubusercontent.com/73720978/97756548-2a3ded80-1b4f-11eb-8bd9-a9ced0c89b35.png)

---
and a bug with absolute glare which absolute glare not transferable with x1 or x2. this is incorrect
![image](https://user-images.githubusercontent.com/73720978/97756667-5f4a4000-1b4f-11eb-8b21-ae290780198b.png)

**Comment by malulleybovo** [comment]
Issue has been fixed in v1.2.2.
