### ISSUE TITLE
Absolute Glare incorrect recipes

### ISSUE THREAD

**Issue by MusouMiko** [malulleybovo/PSO2AffixingAssistant#46]
Currently the assistant says you can transfer absolute glare at a 30% rate, or a 50% rate with two of them. You can't transfer Absolute Glare at all actually.

**Comment by nandadytm** [comment]
Hello, it's fixed on PR #45. Please wait until malulley merge it, or use [this](https://fullcounterr.github.io/PSO2AffixingAssistant/) fork for the time being

**Comment by malulleybovo** [comment]
Issue has been fixed in v1.2.2.
