### ISSUE TITLE
Exceed Receptor is not shown as a use item

### ISSUE THREAD

**Issue by Yazuka** [malulleybovo/PSO2AffixingAssistant#48]
**Describe the bug**
Exceed Receptor is missing as a use item, when you select the affix in your plan, it specifies that this can't be affixed so you're forced to make a fodder which is only this affix and this affix alone that can make some plans improbable / impossible.

**To Reproduce**
1. Add the Exceed Energy affix to your plan
2. Select transplant it
3. Click the affix it button
4. Confirm your choice
5. See that Exceed Receptor can't be affixed

**Expected behavior**
You're able to specify Exceed Receptor as a use item similar to Divine Receptor etc

**Screenshots**
![image](https://user-images.githubusercontent.com/2867729/100947447-940a3800-34fd-11eb-8aea-6eda1f0325e0.png)

**Additional context**
The item is called 特殊能力（イクシード継承）or Add Ability (Exceed Receptor) and can be seen here: http://www.bumped.org/psublog/pso2-jp-sg-scratch-support-item-selection/

**Comment by malulleybovo** [comment]
Thank you for reporting this issue as well as for the information provided. This will be included in the assistant as soon as I find time to work on this

**Comment by malulleybovo** [comment]
A big update is in the making that addresses this and many other things.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
