### ISSUE TITLE
Why there is no option for Ether factor as a SAF?

### ISSUE THREAD

**Issue by funggy** [malulleybovo/PSO2AffixingAssistant#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mabinogi-delight** [comment]
It is mistranslated as "Aether Factor" in NA.
Similar things happens to "Toh'oh Soul" which is called "Eastern Soul" in NA.

**Comment by malulleybovo** [comment]
Thank you for reporting. That is most likely due to the Assistant becoming outdated since the last update. As soon as I find time to put in this project, there will be one big database update for the newer abilities and newer transfer methods.

**Comment by malulleybovo** [comment]
As for the translation question, although a different topic from the one in this issue, is being tackled in one of the active pull requests.

**Comment by malulleybovo** [comment]
A big update is in the making that addresses this and many other things.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
