### ISSUE TITLE
Glare Catalyst impossible combinations

### ISSUE THREAD

**Issue by random-assistant** [malulleybovo/PSO2AffixingAssistant#52]
**Describe the bug**
In the simulator, it is allowed to combine 2 or 3 Glare Catalysts for 10% or 30% chance of affixing Glare Catalyst onto a unit. This is false as I have attempted this in-game already. I can see why this option may have been added, as Soul Catalyst, Factor Catalyst, Reverie Catalyst allow you to affix multiple of its type to bring it over to a unit/weapon. However Glare Catalyst is an exception.

**To Reproduce**
1. Go to the Sim and try to make something like Glare Catalyst by itself or Glare Catalyst with Crack IV.
2. When affixing, you will see the option for (x2) Glare Catalyst or (x3) Glare Catalyst for 10% or 30% chance to affix Glare Catalyst.
3. Go in game and have the same fodder as presented in the sim.
4. Option will not be available to select Glare Catalyst in final affix.

**Expected behavior**
Expected Glare Catalyst to show up in the menu when having 2 or 3 of it selected during affixing, but does not.

**Screenshots**
![image](https://user-images.githubusercontent.com/77815098/105430022-3601f300-5c18-11eb-8f29-9b2b6fd36148.png)
![image](https://user-images.githubusercontent.com/77815098/105430135-73ff1700-5c18-11eb-944c-0553bbdc5800.png)

**Additional context**
This is on the NA version of PSO2. I assume this is also true of JP PSO2 as I did not see this combination of Glare Catalyst doable on the arks-layer version of their affix simulator.

**Comment by malulleybovo** [comment]
Thank you for reporting and I apologize for the inconvenience in case you tried the incorrect formula in game for real. It seems like this incorrect formula was not filtered out when being ported over to the Assistant. I will update this issue as soon as it is fixed.

**Comment by Jwguy0** [comment]
Wasted 30 million meseta and have to replan my whole unit set because of this, and came to report it. Kind of surprised to see this has been going on since February.

**Comment by malulleybovo** [comment]
A big update is in the making that addresses this and many other things.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
