### ISSUE TITLE
Selected Position of Abilities on Fodder Doesn't Match Resulting Node After Confirming.

### ISSUE THREAD

**Issue by AriahPSO2** [malulleybovo/PSO2AffixingAssistant#54]
**Describe the bug**
When selecting which fodder you want abilities to be on, if the result does not use all fodders, and the main fodder is full of junk, the resulting node may put abilities on the wrong fodder. If the resulting node decides to use 3 fodder total, it seems to remove fodder from left to right that were full of junk until there are 3 remaining. This includes the main fodder. Due to this, the resulting node will treat the first remaining fodder as the main fodder, even if you specified that the main fodder should be full of junk.

**To Reproduce**
1. Start a new affixing goal. Choose 1 ability such as Power I and click affix.
2. Choose the first option "100% : Power I" and confirm.
3. Move Power I from the main fodder to Fodder 1, Fodder 2, or Fodder 3. Choosing Fodder 4 or 5 will result in the junk Fodder 3 being used as the main fodder, so choose 1, 2, or 3. Click Confirm.
4. The resulting node will show Power I on the main fodder.

**Expected behavior**
The resulting node should show the main fodder full of junk.

**Screenshots**
![image](https://user-images.githubusercontent.com/78177863/106202212-94ceeb80-6187-11eb-987c-a3922810ee17.png)

![image](https://user-images.githubusercontent.com/78177863/106202276-ac0dd900-6187-11eb-83b3-e2917c8321fe.png)

**Comment by malulleybovo** [comment]
Thank you for reporting. I will make sure to include this fix as soon as I get time to put into this project. Until then, as a workaround, you can pretend Fodder 1 is your Main Fodder since they are just names to make it clearer to who is using the Assistant but do not have any functional difference between them.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
