### ISSUE TITLE
Add Reverie Receptor

### ISSUE THREAD

**Issue by ronelm2000** [malulleybovo/PSO2AffixingAssistant#57]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/12634987/108168605-91010a00-7132-11eb-803b-2983a68e6fc7.png)
PSO2 Global is introducing Reverie Receptor here, and Reverie Receptor recipes are not on Affix Assistant yet.
Source: https://pso2.com/news/announcements/newcontent0217

**Describe the solution you'd like**
Addition of formulas involving Reverie Receptor on the assistant. 

**Describe alternatives you've considered**
N/A, This affects affixing recipes.

**Additional context**
This issue should be a heads up to @CorVous et al. on their Global translation fork.
A pull request is found here (not by me) since 20 days ago: #53

**Comment by malulleybovo** [comment]
Thank you for reporting. A big update is in the making that addresses this and many other things.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
