### ISSUE TITLE
Reverie Receptor missing

### ISSUE THREAD

**Issue by AliasOfMine** [malulleybovo/PSO2AffixingAssistant#58]
**Is your feature request related to a problem? Please describe.**
Reverie Receptor is important for stuff x.x

**Describe the solution you'd like**
can do haz receptor kindly

**Describe alternatives you've considered**
nope, plez do

**Additional context**
love your cite <3

**Comment by malulleybovo** [comment]
Thank you for reporting. A big update is in the making that addresses this and many other things.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
