### ISSUE TITLE
Missing +20% boost week

### ISSUE THREAD

**Issue by arpakasso** [malulleybovo/PSO2AffixingAssistant#59]
Sega is doing 20% boost week in PSO2NA, would be really helpful to have. Thanks for this great site! 👍 

[ZERO MESETA COST ENHANCEMENT (and Boosts!)](https://pso2.com/news/announcements/campaignsmar2020p2)

**Comment by malulleybovo** [comment]
Thank you for reporting. A big update is in the making that addresses this and many other things.

**Comment by malulleybovo** [comment]
Issue has been addressed in v1.3.0.
